scss_files: 'src/sass/style.scss'

exclude: 'src/sass/_normalize/scss'

linters:
  StringQuotes:
    enabled: true
    style: double_quotes


  LeadingZero:
    enabled: true
    style: include_zero

  SpaceAfterPropertyColon:
    enabled: false

  VendorPrefix:
    enabled: false
